Zephyr: fix GATT/SR/GAS/BV-01-C
intel/auto-pts pull request #515
Opened 2021-07-15 07:18 UTC by KKopyscinski

We need to add two different services, so randomize UUID to avoid
duplication

2021-07-15 07:19 UTC, KKopyscinski commented
This test also required patched `.ets` file from CASE0071492

2021-07-15 08:01 UTC, sjanc commented
hmm could we make it predictable?  eg toggle registration of two known UUIDs?

2021-07-15 08:04 UTC, KKopyscinski commented
Well, maybe add flag marking if wid 96 was run before? And register different UUID second time

2021-07-15 08:16 UTC, KKopyscinski commented
The problem is that we do not register it in wid 96, we do it after it returns, that's why I made it this way. So we are limited to what we can do using `TestFunc()`

2021-07-15 08:29 UTC, KKopyscinski commented
OK, we just need to register the same TestFunc twice, with different UUIDs, no need for randomization :)

2021-07-15 09:45 UTC, sjanc approved these changes

2021-07-15 09:45 UTC, sjanc requested changes

2021-07-15 09:45 UTC, sjanc commented on ptsprojects/zephyr/gatt.py
> +from random import randint
so this is no longer needed, tight?

2021-07-21 08:50 UTC, michal-narajowski requested changes
Also needs a rebase and conflicts resolved.

2021-07-21 09:12 UTC, KKopyscinski commented
@michal-narajowski Fixed and rebased

2021-07-21 11:02 UTC, sjanc approved these changes

2021-07-21 11:07 UTC, michal-narajowski approved these changes

2021-07-21 11:07 UTC, merged