GAP: added option to set filter accept list
intel/auto-pts pull request #640
Opened 2021-11-08 13:40 UTC by jrotkiewicz

Dialog board sends 0 after reset. Added fix to discard this zero.
Divided PR: https://github.com/intel/auto-pts/pull/585

2021-11-08 13:40 UTC, jrotkiewicz commented
@michal-narajowski

2021-11-09 14:21 UTC, michal-narajowski requested changes

2021-11-09 14:21 UTC, michal-narajowski commented on doc/btp_spec.txt
> +		Address 00:00:00:00:00:00 will attempt to use address
Address should be 00:00:00:00:00:00 and address type should be 0

2021-11-09 14:21 UTC, michal-narajowski commented on doc/btp_spec.txt
> +		Command parameters:
```suggestion
		Controller Index: <controller id>
		Command parameters:
```

2021-11-09 14:21 UTC, michal-narajowski commented on doc/btp_spec.txt
> +	Opcode 0x1f - Set filter accept list
```suggestion
	Opcode 0x1c - Set filter accept list
```

2021-11-09 14:21 UTC, michal-narajowski commented on doc/btp_spec.txt
> +		When set, connect with address: 00:00:00:00:00:00
address 0 and type 0.

2021-11-09 14:21 UTC, michal-narajowski commented on doc/btp_spec.txt
> +				addr_tup = [('11:22:33:44:55:66', 0), ...]
```suggestion
```

2021-11-09 14:21 UTC, michal-narajowski commented on doc/btp_spec.txt
> +			Address tuples:
```suggestion
			Address_Type #N (1 octet)
			Address #N (6 octets)
			for N from 1 to the number of addresses in the filter accept list.
```

2021-11-09 14:21 UTC, michal-narajowski commented on pybtp/btp/gap.py
> +    if addr_tup == None:
```suggestion
    if not address_list:
        address_list = [(pts_addr_get(None), pts_addr_type_get(None))]
    
    for addr, type in address_list:
            bd_addr_ba = addr2btp_ba(addr)
            bd_addr_type_ba = chr(type).encode('utf-8')
            data_ba.extend(bd_addr_type_ba)
            data_ba.extend(bd_addr_ba)
    
    
```

2021-11-09 14:21 UTC, michal-narajowski commented on pybtp/btp/gap.py
> +def set_filter_accept_list(addr_tup=None):
```suggestion
def set_filter_accept_list(address_list=None):
```

2021-11-10 07:14 UTC, jrotkiewicz commented
@michal-narajowski

2021-11-23 11:11 UTC, michal-narajowski approved these changes

2021-11-23 11:11 UTC, merged