GATT Client service: add commands and events
intel/auto-pts pull request #671
Opened 2021-12-20 11:35 UTC by KKopyscinski

2022-02-24 09:09 UTC, KKopyscinski commented
@sjanc @mkasenberg I marked this as ready for review, I think this could be used as base for later, only thing that is left is possible changes that were added in meanwhile in https://github.com/intel/auto-pts/pull/620 and implementetion of some WIDs.

2022-03-01 09:17 UTC, mkasenberg commented on wid/gatt_client.py
> +    print(stack.gatt_cl.chrcs)
debug leftovers

2022-03-24 11:21 UTC, michal-narajowski requested changes

2022-03-25 06:23 UTC, KKopyscinski commented on ptsprojects/stack.py
> +        return False
Added commit that simplifies this

2022-03-30 10:03 UTC, michal-narajowski commented
Rebase please.

2022-03-30 10:42 UTC, KKopyscinski commented
> Rebase please.

done

2022-03-30 10:43 UTC, michal-narajowski approved these changes

2022-03-30 10:43 UTC, merged