Zephyr: fix the link of guide
intel/auto-pts pull request #820
Opened 2022-10-23 17:16 UTC by supperthomas

Signed-off-by: supperthomas <78900636@qq.com>

2022-10-24 05:42 UTC, MariuszSkamra requested changes
Nice catch, could you please use the links to the Zephyr documentation instead?

2022-10-24 05:42 UTC, MariuszSkamra commented on README.md
> +  https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/connectivity/bluetooth/autopts/autopts-linux.rst
https://docs.zephyrproject.org/latest/connectivity/bluetooth/autopts/autopts-linux.html

2022-10-24 05:42 UTC, MariuszSkamra commented on README.md
> +  https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/connectivity/bluetooth/autopts/autopts-win10.rst
https://docs.zephyrproject.org/latest/connectivity/bluetooth/autopts/autopts-win10.html

2022-10-24 14:26 UTC, supperthomas commented
done

2022-10-26 06:01 UTC, MariuszSkamra approved these changes

2022-10-26 06:01 UTC, merged