Add support to select dongle
intel/auto-pts pull request #843
Opened 2022-12-18 15:14 UTC by justin-nxp

this can add support to selected dongle，Adding the --dongle parameter allows two boards to be tested at the same time, greatly reducing testing time

2022-12-19 07:41 UTC, sjanc approved these changes

2022-12-19 08:30 UTC, michal-narajowski requested changes

2022-12-19 08:30 UTC, michal-narajowski commented on autopts/ptscontrol.py
>          for device in devices:
I think we will still override device_to_connect in this `for` loop, so your change will have no effect.

2022-12-19 08:30 UTC, michal-narajowski commented on autopts/ptscontrol.py
> +            log("slecte dongle :", device)
```suggestion
            log("selected dongle :", device)
```

2023-01-12 11:48 UTC, michal-narajowski commented
@justin-nxp Any update on this?

2023-01-16 11:52 UTC, closed without merging